
server:
  port: 7899
github:
  apiToken: ENC(ftsaQe3qHWmudFx3qWWCm1Re57SX3Rlr8MjHWVMoMV9deAT8shWJTrO8haYxy+r/mapcr6V/dSxb4lgXomrRrF7Siah5CZvDrW4KNwBD/B48b/vUkXF2Hwsj6jfKerqpKn5mE/KyAjsiANkalwBJJDVsHoG3Lw4Sl30PCgMqI2o=)
jasypt:
  encryptor:
    password: secret-key

